name: CI/CD Demo Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  continuous-integration:
    runs-on: ubuntu-latest  # Run job on the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify Node.js version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run Tests
        run: npm test

  continuous-deployment:
    needs: continuous-integration  # Run this job only after continuous-integration is successful
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to a mock deployment script
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          echo "Deployment complete."
